const githubResult = """
    {
  "total_count": 13,
  "incomplete_results": false,
  "items": [
    {
      "login": "guiima",
      "id": 39744827,
      "node_id": "MDQ6VXNlcjM5NzQ0ODI3",
      "avatar_url": "https://avatars.githubusercontent.com/u/39744827?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiima",
      "html_url": "https://github.com/guiima",
      "followers_url": "https://api.github.com/users/guiima/followers",
      "following_url": "https://api.github.com/users/guiima/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiima/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiima/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiima/subscriptions",
      "organizations_url": "https://api.github.com/users/guiima/orgs",
      "repos_url": "https://api.github.com/users/guiima/repos",
      "events_url": "https://api.github.com/users/guiima/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiima/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guiimagno",
      "id": 78588805,
      "node_id": "MDQ6VXNlcjc4NTg4ODA1",
      "avatar_url": "https://avatars.githubusercontent.com/u/78588805?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiimagno",
      "html_url": "https://github.com/guiimagno",
      "followers_url": "https://api.github.com/users/guiimagno/followers",
      "following_url": "https://api.github.com/users/guiimagno/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiimagno/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiimagno/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiimagno/subscriptions",
      "organizations_url": "https://api.github.com/users/guiimagno/orgs",
      "repos_url": "https://api.github.com/users/guiimagno/repos",
      "events_url": "https://api.github.com/users/guiimagno/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiimagno/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guiimarques18",
      "id": 1537504,
      "node_id": "MDQ6VXNlcjE1Mzc1MDQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1537504?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiimarques18",
      "html_url": "https://github.com/guiimarques18",
      "followers_url": "https://api.github.com/users/guiimarques18/followers",
      "following_url": "https://api.github.com/users/guiimarques18/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiimarques18/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiimarques18/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiimarques18/subscriptions",
      "organizations_url": "https://api.github.com/users/guiimarques18/orgs",
      "repos_url": "https://api.github.com/users/guiimarques18/repos",
      "events_url": "https://api.github.com/users/guiimarques18/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiimarques18/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Guiimartinho",
      "id": 41489663,
      "node_id": "MDQ6VXNlcjQxNDg5NjYz",
      "avatar_url": "https://avatars.githubusercontent.com/u/41489663?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Guiimartinho",
      "html_url": "https://github.com/Guiimartinho",
      "followers_url": "https://api.github.com/users/Guiimartinho/followers",
      "following_url": "https://api.github.com/users/Guiimartinho/following{/other_user}",
      "gists_url": "https://api.github.com/users/Guiimartinho/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Guiimartinho/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Guiimartinho/subscriptions",
      "organizations_url": "https://api.github.com/users/Guiimartinho/orgs",
      "repos_url": "https://api.github.com/users/Guiimartinho/repos",
      "events_url": "https://api.github.com/users/Guiimartinho/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Guiimartinho/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GuiiMazza",
      "id": 41164223,
      "node_id": "MDQ6VXNlcjQxMTY0MjIz",
      "avatar_url": "https://avatars.githubusercontent.com/u/41164223?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GuiiMazza",
      "html_url": "https://github.com/GuiiMazza",
      "followers_url": "https://api.github.com/users/GuiiMazza/followers",
      "following_url": "https://api.github.com/users/GuiiMazza/following{/other_user}",
      "gists_url": "https://api.github.com/users/GuiiMazza/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GuiiMazza/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GuiiMazza/subscriptions",
      "organizations_url": "https://api.github.com/users/GuiiMazza/orgs",
      "repos_url": "https://api.github.com/users/GuiiMazza/repos",
      "events_url": "https://api.github.com/users/GuiiMazza/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GuiiMazza/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GuiiMaranhao",
      "id": 52301648,
      "node_id": "MDQ6VXNlcjUyMzAxNjQ4",
      "avatar_url": "https://avatars.githubusercontent.com/u/52301648?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GuiiMaranhao",
      "html_url": "https://github.com/GuiiMaranhao",
      "followers_url": "https://api.github.com/users/GuiiMaranhao/followers",
      "following_url": "https://api.github.com/users/GuiiMaranhao/following{/other_user}",
      "gists_url": "https://api.github.com/users/GuiiMaranhao/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GuiiMaranhao/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GuiiMaranhao/subscriptions",
      "organizations_url": "https://api.github.com/users/GuiiMaranhao/orgs",
      "repos_url": "https://api.github.com/users/GuiiMaranhao/repos",
      "events_url": "https://api.github.com/users/GuiiMaranhao/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GuiiMaranhao/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GuiiMattoss",
      "id": 49915257,
      "node_id": "MDQ6VXNlcjQ5OTE1MjU3",
      "avatar_url": "https://avatars.githubusercontent.com/u/49915257?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GuiiMattoss",
      "html_url": "https://github.com/GuiiMattoss",
      "followers_url": "https://api.github.com/users/GuiiMattoss/followers",
      "following_url": "https://api.github.com/users/GuiiMattoss/following{/other_user}",
      "gists_url": "https://api.github.com/users/GuiiMattoss/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GuiiMattoss/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GuiiMattoss/subscriptions",
      "organizations_url": "https://api.github.com/users/GuiiMattoss/orgs",
      "repos_url": "https://api.github.com/users/GuiiMattoss/repos",
      "events_url": "https://api.github.com/users/GuiiMattoss/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GuiiMattoss/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guiimariano",
      "id": 31457675,
      "node_id": "MDQ6VXNlcjMxNDU3Njc1",
      "avatar_url": "https://avatars.githubusercontent.com/u/31457675?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiimariano",
      "html_url": "https://github.com/guiimariano",
      "followers_url": "https://api.github.com/users/guiimariano/followers",
      "following_url": "https://api.github.com/users/guiimariano/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiimariano/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiimariano/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiimariano/subscriptions",
      "organizations_url": "https://api.github.com/users/guiimariano/orgs",
      "repos_url": "https://api.github.com/users/guiimariano/repos",
      "events_url": "https://api.github.com/users/guiimariano/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiimariano/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guiimarra",
      "id": 71839242,
      "node_id": "MDQ6VXNlcjcxODM5MjQy",
      "avatar_url": "https://avatars.githubusercontent.com/u/71839242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiimarra",
      "html_url": "https://github.com/guiimarra",
      "followers_url": "https://api.github.com/users/guiimarra/followers",
      "following_url": "https://api.github.com/users/guiimarra/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiimarra/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiimarra/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiimarra/subscriptions",
      "organizations_url": "https://api.github.com/users/guiimarra/orgs",
      "repos_url": "https://api.github.com/users/guiimarra/repos",
      "events_url": "https://api.github.com/users/guiimarra/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiimarra/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guiimassongt",
      "id": 62115749,
      "node_id": "MDQ6VXNlcjYyMTE1NzQ5",
      "avatar_url": "https://avatars.githubusercontent.com/u/62115749?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiimassongt",
      "html_url": "https://github.com/guiimassongt",
      "followers_url": "https://api.github.com/users/guiimassongt/followers",
      "following_url": "https://api.github.com/users/guiimassongt/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiimassongt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiimassongt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiimassongt/subscriptions",
      "organizations_url": "https://api.github.com/users/guiimassongt/orgs",
      "repos_url": "https://api.github.com/users/guiimassongt/repos",
      "events_url": "https://api.github.com/users/guiimassongt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiimassongt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "guiimaraes",
      "id": 102600797,
      "node_id": "U_kgDOBh2QXQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/102600797?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/guiimaraes",
      "html_url": "https://github.com/guiimaraes",
      "followers_url": "https://api.github.com/users/guiimaraes/followers",
      "following_url": "https://api.github.com/users/guiimaraes/following{/other_user}",
      "gists_url": "https://api.github.com/users/guiimaraes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/guiimaraes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/guiimaraes/subscriptions",
      "organizations_url": "https://api.github.com/users/guiimaraes/orgs",
      "repos_url": "https://api.github.com/users/guiimaraes/repos",
      "events_url": "https://api.github.com/users/guiimaraes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/guiimaraes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "GuiiMaia",
      "id": 82165655,
      "node_id": "MDQ6VXNlcjgyMTY1NjU1",
      "avatar_url": "https://avatars.githubusercontent.com/u/82165655?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/GuiiMaia",
      "html_url": "https://github.com/GuiiMaia",
      "followers_url": "https://api.github.com/users/GuiiMaia/followers",
      "following_url": "https://api.github.com/users/GuiiMaia/following{/other_user}",
      "gists_url": "https://api.github.com/users/GuiiMaia/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/GuiiMaia/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/GuiiMaia/subscriptions",
      "organizations_url": "https://api.github.com/users/GuiiMaia/orgs",
      "repos_url": "https://api.github.com/users/GuiiMaia/repos",
      "events_url": "https://api.github.com/users/GuiiMaia/events{/privacy}",
      "received_events_url": "https://api.github.com/users/GuiiMaia/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Guiimalveira",
      "id": 70438091,
      "node_id": "MDQ6VXNlcjcwNDM4MDkx",
      "avatar_url": "https://avatars.githubusercontent.com/u/70438091?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Guiimalveira",
      "html_url": "https://github.com/Guiimalveira",
      "followers_url": "https://api.github.com/users/Guiimalveira/followers",
      "following_url": "https://api.github.com/users/Guiimalveira/following{/other_user}",
      "gists_url": "https://api.github.com/users/Guiimalveira/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Guiimalveira/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Guiimalveira/subscriptions",
      "organizations_url": "https://api.github.com/users/Guiimalveira/orgs",
      "repos_url": "https://api.github.com/users/Guiimalveira/repos",
      "events_url": "https://api.github.com/users/Guiimalveira/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Guiimalveira/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
